import { Hall, StudentSet, SeatingPlan, User, HallTemplate, StudentSetTemplate, SeatDefinition, AuditLog, Exam, Role } from "../types";
import { apiRpc } from "../lib/api";

export const getAuditLogs = (adminId: string): Promise<AuditLog[]> => apiRpc("getAuditLogs", adminId);
export const getAllAdmins = (): Promise<User[]> => apiRpc("getAllAdmins");
export const grantAdminPermission = (adminId: string): Promise<User | undefined> => apiRpc("grantAdminPermission", adminId);
export const deleteAdminAndInstitution = (adminId: string): Promise<boolean> => apiRpc("deleteAdminAndInstitution", adminId);
export const getInstitutions = (): Promise<{ id: string; name: string }[]> => apiRpc("getInstitutions");
export const findUserById = (id: string): Promise<User | undefined> => apiRpc("findUserById", id);
export const getTeachersForAdmin = (adminId: string): Promise<User[]> => apiRpc("getTeachersForAdmin", adminId);
export const getUnassignedTeachers = (): Promise<User[]> => apiRpc("getUnassignedTeachers");
export const grantTeacherPermission = (teacherId: string, adminId: string): Promise<User | undefined> => apiRpc("grantTeacherPermission", teacherId, adminId);
export const revokeTeacherPermission = (teacherId: string): Promise<User | undefined> => apiRpc("revokeTeacherPermission", teacherId);
export const deleteTeacher = (teacherId: string, adminId: string): Promise<boolean> => apiRpc("deleteTeacher", teacherId, adminId);
export const getExamsForAdmin = (adminId: string): Promise<Exam[]> => apiRpc("getExamsForAdmin", adminId);
export const getExamsForStudent = (registerNumber: string, adminId: string): Promise<Exam[]> => apiRpc("getExamsForStudent", registerNumber, adminId);
export const getExamsForTeacher = (teacherId: string): Promise<Exam[]> => apiRpc("getExamsForTeacher", teacherId);
export const createExam = (examData: any, teacherId: string): Promise<Exam> => apiRpc("createExam", examData, teacherId);
export const updateExam = (updatedExam: Exam): Promise<Exam> => apiRpc("updateExam", updatedExam);
export const updateExamSeatingPlan = (examId: string, newPlan: SeatingPlan, updaterId: string): Promise<boolean> => apiRpc("updateExamSeatingPlan", examId, newPlan, updaterId);
export const deleteExam = (examId: string, ownerId: string, role: Role): Promise<boolean> => apiRpc("deleteExam", examId, ownerId, role);
export const getHallTemplatesForTeacher = (teacherId: string): Promise<HallTemplate[]> => apiRpc("getHallTemplatesForTeacher", teacherId);
export const getHallTemplatesForAdmin = (adminId: string): Promise<HallTemplate[]> => apiRpc("getHallTemplatesForAdmin", adminId);
export const createHallTemplate = (templateData: any, creatorId: string): Promise<HallTemplate> => apiRpc("createHallTemplate", templateData, creatorId);
export const updateHallTemplate = (templateId: string, data: any, updaterId: string): Promise<HallTemplate | null> => apiRpc("updateHallTemplate", templateId, data, updaterId);
export const deleteHallTemplate = (templateId: string, deleterId: string, role: Role): Promise<boolean> => apiRpc("deleteHallTemplate", templateId, deleterId, role);
export const getStudentSetTemplatesForTeacher = (teacherId: string): Promise<StudentSetTemplate[]> => apiRpc("getStudentSetTemplatesForTeacher", teacherId);
export const getStudentSetTemplatesForAdmin = (adminId: string): Promise<StudentSetTemplate[]> => apiRpc("getStudentSetTemplatesForAdmin", adminId);
export const createStudentSetTemplate = (templateData: any, creatorId: string): Promise<StudentSetTemplate> => apiRpc("createStudentSetTemplate", templateData, creatorId);
export const updateStudentSetTemplate = (templateId: string, data: any, updaterId: string): Promise<StudentSetTemplate | null> => apiRpc("updateStudentSetTemplate", templateId, data, updaterId);
export const deleteStudentSetTemplate = (templateId: string, deleterId: string, role: Role): Promise<boolean> => apiRpc("deleteStudentSetTemplate", templateId, deleterId, role);
export const generateClassicSeatingPlan = (examData: { halls: Hall[]; studentSets: StudentSet[]; seatingType?: "normal" | "fair" }): Promise<{ plan: SeatingPlan | null; message?: string }> => apiRpc("generateClassicSeatingPlan", examData);
export const generateSeatingPlan = (examData: { halls: Hall[]; studentSets: StudentSet[]; rules: string; seatingType: "normal" | "fair"; editorMode: "ai" | "classic" | "advanced" | "ai-advanced" }): Promise<{ plan: SeatingPlan | null; message?: string }> => apiRpc("generateSeatingPlan", examData);
export const generateLayoutFromImage = (base64Image: string, mimeType: string): Promise<{ layout: SeatDefinition[]; rows: number; cols: number } | null> => apiRpc("generateLayoutFromImage", base64Image, mimeType);
